from datetime import datetime
from typing import Protocol

from src.domain.entities import Expense, Participant, Room, User
from src.domain.enums import ExpenseKind, SplitType


class UserRepo(Protocol):
    async def get(self, user_id: int) -> User | None: ...

    async def get_by_telegram_id(self, telegram_id: int) -> User | None: ...

    async def create(self, telegram_id: int, username: str | None, first_name: str) -> User: ...

    async def update_profile(self, user_id: int, username: str | None, first_name: str) -> None: ...


class RoomRepo(Protocol):
    async def create(
        self, *, title: str, owner_user_id: int, invite_token: str, currency: str
    ) -> Room: ...

    async def get(self, room_id: int) -> Room | None: ...

    async def get_by_invite_token(self, token: str) -> Room | None: ...

    async def list_for_user(self, user_id: int) -> list[Room]: ...

    async def count_for_user(self, user_id: int) -> int: ...

    async def set_archived(self, room_id: int, archived: bool) -> None: ...

    async def set_invite_token(self, room_id: int, token: str) -> None: ...

    async def delete(self, room_id: int) -> None: ...

    async def touch_activity(self, room_id: int) -> None: ...

    async def mark_deletion_notified(self, room_id: int) -> None: ...

    async def list_to_notify(self, inactive_since: datetime) -> list[Room]: ...

    async def list_to_delete(self, notified_before: datetime) -> list[Room]: ...


class ParticipantRepo(Protocol):
    async def add(self, room_id: int, user_id: int | None, display_name: str) -> Participant: ...

    async def get(self, participant_id: int) -> Participant | None: ...

    async def get_by_room_and_user(self, room_id: int, user_id: int) -> Participant | None: ...

    async def list_by_room(
        self, room_id: int, include_inactive: bool = False
    ) -> list[Participant]: ...

    async def list_with_usernames(
        self, room_id: int, include_inactive: bool = False
    ) -> list[tuple[Participant, str | None]]: ...

    async def count_active(self, room_id: int) -> int: ...

    async def set_active(self, participant_id: int, active: bool) -> None: ...


class ExpenseRepo(Protocol):
    async def add(
        self,
        *,
        room_id: int,
        kind: ExpenseKind,
        paid_by_participant_id: int,
        amount: int,
        description: str,
        split_type: SplitType,
        created_by_user_id: int,
        shares: dict[int, int],
        currency: str,
    ) -> Expense: ...

    async def get(self, expense_id: int) -> Expense | None: ...

    async def update_description(self, expense_id: int, description: str) -> None: ...

    async def update_amount(self, expense_id: int, amount: int, shares: dict[int, int]) -> None: ...

    async def update_payer(self, expense_id: int, participant_id: int) -> None: ...

    async def update_shares(self, expense_id: int, shares: dict[int, int]) -> None: ...

    async def delete(self, expense_id: int) -> None: ...

    async def list_page(self, room_id: int, offset: int, limit: int) -> list[Expense]: ...

    async def count(self, room_id: int) -> int: ...

    async def expense_stats(self, room_id: int) -> tuple[int, int]: ...

    async def paid_totals(self, room_id: int) -> dict[int, int]: ...

    async def owed_totals(self, room_id: int) -> dict[int, int]: ...
